{{- $root := . -}}
{{- range $service := .Values.Services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }} 
  labels:
    app.kubernetes.io/name: {{ $service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }} 
          image: {{ $root.Values.image }}
          imagePullPolicy: IfNotPresent
 
          env:
            - name: VirtServerUserRole
              value: ADMIN
            - name: VirtServerUser
              value: defaultUser
            - name: VirtServerPassword
              value: svp4ever
            - name: UseHTTPS
              value: "false"
            - name: ACCEPT_TOU
              value: "true"
            - name: SlmServerUrl
              value: {{ $root.Values.licenseServer }}
            - name: SlmAccessKey
              value: {{ $root.Values.SlmAccessKey }}
            - name: CONFIG
              value: /virtserver/myconfig.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /virtserver/myconfig.yaml # Mount the ConfigMap as /myconfig.yaml
              subPath: config.yaml # Use the key from the ConfigMap
          ports:
            - containerPort: 9090
              name: virtserver
             {{ range $i, $e := untilStep (index $service.exposePorts 0 | int) (index $service.exposePorts 1 | add 1 | int) 1 }}
            - name: virt-port-{{$e}}
              containerPort: {{$e}}
            {{ end }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/v3/info/about/
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/v3/info/about/
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: config-volume
          configMap:
            name: virtserver-configmap 
---
{{- end }}