apiVersion: apps/v1
kind: Deployment
metadata:
  name: ready-api-virtserver
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: ready-api-virtserver
  template:
    metadata:
      annotations:
        rollme: {{ uuidv4 }}
      labels:
        run: ready-api-virtserver
    spec:
      containers:
        - name: ready-api-virtserver
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: VirtServerUserRole
              value: ADMIN
            - name: VirtServerUser
              value: defaultUser
            - name: VirtServerPassword
              value: svp4ever
            - name: UseHTTPS
              value: "true"
            - name: ACCEPT_TOU
              value: "true"
            - name: VirtServerLicenseServer
              value: {{ .Values.licenseServer }}
            - name: SlmAccessKey
              value: {{ .Values.SlmAccessKey }}
          volumeMounts:
            - name: virtserver-config-folder
              mountPath: /virtserver
              readOnly: false
          ports:
            - containerPort: 9090
              name: virtserver
            {{ range $i, $e := untilStep (index .Values.exposePorts 0 | int) (index .Values.exposePorts 1 | int) 1 }}
            - containerPort: {{$e | int}}
            {{ end }}
          resources:
            requests:
              memory: {{ .Values.requests.memory }}
              cpu: {{ .Values.requests.cpu }}
            limits:
              memory: {{ .Values.limits.memory }}
              cpu: {{ .Values.limits.cpu }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /api/v3/info/about/
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /api/v3/info/about/
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: virtserver-config-folder
          persistentVolumeClaim:
            claimName: virtserver-config-folder
