apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtserver-config-folder
  labels:
    run: ready-api-virtserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configStorageSize }}