apiVersion: v1
kind: Service
metadata:
  name: ready-api-virtserver
  labels:
    run: ready-api-virtserver
spec:
  type: LoadBalancer
  ports:
    - name: admin
      port: 9090
    {{ range $i, $e := untilStep (index .Values.exposePorts 0 | int) (index .Values.exposePorts 1 | add 1 | int) 1 }}
    - name: virt-port-{{$e}}
      port: {{$e}}
    {{ end }}
  selector:
    run: ready-api-virtserver