{{- $root := . -}}
{{- range $service := .Values.Services }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ $service.name }} 
  labels:
spec:
  type: NodePort
  ports:
    - name: admin
      port: 9090
    {{ range $i, $e := untilStep (index $service.exposePorts 0 | int) (index $service.exposePorts 1 | add 1 | int) 1 }}
    - name: virt-port-{{$e}}
      port: {{$e}}
    {{ end }}
  selector:
    app.kubernetes.io/name: {{ $service.name }}
---
{{- end }}